# Generated by Django 5.1 on 2024-08-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAuthUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255)),
                ('mws_auth_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Amazon Auth User',
                'verbose_name_plural': 'Amazon Auth Users',
                'db_table': 'amazon_auth_users',
                'ordering': ['-created_at'],
            },
        ),
    ]
