# Generated by Django 5.1 on 2024-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_partner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amazon_state', models.CharField(blank=True, max_length=255, null=True)),
                ('amazon_callback_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Amazon Auth',
                'verbose_name_plural': 'Amazon Auths',
                'db_table': 'amazon_auth',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AmazonAuthUsers',
        ),
    ]
