# Generated by Django 4.2.15 on 2024-08-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0002_amazonauth_delete_amazonauthusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refresh_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AmazonAuth',
        ),
    ]
