# Generated by Django 4.2.15 on 2024-09-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0004_alter_refresh_token_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refresh_token',
            options={'permissions': [('can_manage_refresh_tokens', 'Can manage Refresh Tokens')], 'verbose_name': 'Refresh Token', 'verbose_name_plural': 'Refresh Tokens'},
        ),
    ]
