# Generated by Django 5.1.1 on 2024-09-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppOrders',
            new_name='AppOrder',
        ),
    ]
